customization_map = {'present': '1', 'absent': '0'}

multiregional_map = {'present': '1', 'absent': '0'}

cloud_map = {'absent': '00', 'AWS': '01', 'AZURE': '02', 'GCP': '03', 'OpenStack': '04'}

platform_map = {("absent",): '00', ("Kubernetes",): "01", ("OpenShift",): "02", ("Kubernetes", "OpenShift"): "03"}

category_map = {
    "FinOps": "00",
    "Lifecycle management": "01",
    "Unutilized resources": "02",
    "Idle and underutilized resources": "03",
    "Rightsizing": "04",
    "Autoscaling": "05",
    "Computing resources optimization": "06",
    "Storage optimization": "07",
    "Reserved instances and savings plan usage": "08",
    "Other cost optimization checks": "09",
    "Tagging": "10",
    "Security": "11",
    "Detect": "12",
    "Identify": "13",
    "Protect": "14",
    "Recover": "15",
    "Detection services": "16",
    "Secure access management": "17",
    "Inventory": "18",
    "Logging": "19",
    "Resource configuration": "20",
    "Vulnerability, patch, and version management": "21",
    "Secure access management": "22",
    "Secure configuration": "23",
    "Secure network configuration": "24",
    "Data protection": "25",
    "API protection": "26",
    "Protective services": "27",
    "Secure development": "28",
    "Key, Secrets, and Certificate management": "29",
    "Network security": "30",
    "Resilience": "31",
    "Monitoring": "32",
    "Access control": "33",
    "Passwordless authentication": "34",
    "Root user access restrictions": "35",
    "MFA enabled": "36",
    "Sensitive API actions restricted": "37",
    "Resource policy configuration": "38",
    "API private access": "39",
    "Resources not publicly accessible": "40",
    "Resources within VPC": "41",
    "Security group configuration": "42",
    "Encryption of data at rest": "43",
    "Encryption of data in transit": "44",
    "Encryption of data at rest and in transit": "45",
    "Data integrity": "46",
    "Data deletion protection": "47",
    "Credentials not hardcoded": "48",
    "Backups enabled": "49",
    "High availability": "50"
}

source_map = {
    'Azure Security Benchmark (V3)': '00',
    'CIS Amazon Web Services Foundations Benchmark v1.2.0': '01',
    'CIS Amazon Web Services Foundations Benchmark v1.4.0': '02',
    'CIS Amazon Web Services Foundations Benchmark v1.5.0': '03',
    'CIS AWS Compute Services Benchmark v1.0.0': '04',
    'CIS AWS EKS Benchmark 1.1.0': '05',
    'CIS AWS End User Compute Services Benchmark v1.0.0': '06',
    'CIS Benchmark Google Cloud Platform Foundation v1.0.0': '07',
    'CIS Benchmark Google Cloud Platform Foundation v1.2.0': '08',
    'CIS Benchmark Google Cloud Platform Foundation v1.3.0': '09',
    'CIS Benchmark Google Cloud Platform Foundation v2.0.0': '10',
    'CIS Google Kubernetes Engine (GKE) Benchmark v1.3.0': '11',
    'CIS Google Kubernetes Engine (GKE) Benchmark v1.4.0': '12',
    'CIS Microsoft Azure Foundations Benchmark v1.4.0': '13',
    'CIS Microsoft Azure Foundations Benchmark v1.5.0': '14',
    'CIS Microsoft Azure Foundations Benchmark v2.0.0': '15',
    'CIS Oracle MySQL Enterprise Edition 8.0 Benchmark v1.2.0': '16',
    'CIS Oracle Database 19 Benchmark v1.0.0': '17',
    'CIS Oracle MySQL Community Server 5.7 Benchmark v2.0.0': '18',
    'CIS PostgreSQL 11 Benchmark 1.0.0': '19',
    'EPAM': '20',
    'NIST SP 800-53 Rev. 5': '21',
    'PCI DSS': '22',
    "CIS Kubernetes Benchmark v1.7.0": "23",
    "CIS RedHat OpenShift Container Platform Benchmark v1.4.0": "24",
    'CIS Amazon Web Services Foundations Benchmark v2.0.0': '25',
    'CIS Google Kubernetes Engine (GKE) Benchmark v1.5.0': '26'
}

service_section_map = {
    'Identity and Access Management': '00',
    'Logging and Monitoring': '01',
    'Networking & Content Delivery': '02',
    'Compute': '03',
    'Storage': '04',
    'Analytics': '05',
    'Databases': '06',
    'Kubernetes Engine': '07',
    'Containers': '08',
    'Security & Compliance': '09',
    'Cryptography & PKI': '10',
    'Machine Learning': '11',
    'End User Computing': '12',
    'Developer Tools': '13',
    'Application Integration': '14',
    'Dataproc': '15',
    'App Engine': '16',
    'AppService': '17',
    'Microsoft Defender for Cloud': '18',
    "API Server": "19",
    "Controller Manager": "20",
    "etcd": "21",
    "General Policies": "22",
    "Pod Security Standards": "23",
    "RBAC and Service Accounts": "24",
    "Scheduler": "25",
    "Secrets Management": "26"
}